name: Deploy

on:
  # Run this workflow whenever a new commit is pushed to main.
  push: 
    branches:
      - main
  # Run this workflow when triggered manually in GitHub’s UI.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: "3.12"
    
      # Install Python dependencies
      - name: Install Python dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt    

      - run: npm ci

      - id: date
        run: echo "date=$(TZ=America/Los_Angeles date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - id: cache-data
        uses: actions/cache@v4
        with:
            path: src/.observablehq/cache
            key: data-${{ hashFiles('src/data/*') }}-${{ steps.date.outputs.date }}

      - run: npm run build
  
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
